#!/bin/bash
# RSP 2010-09-16
echo
echo "Getperl - Copyright (c) 2010 Rafal Pocztarski"
echo "This program comes with ABSOLUTELY NO WARRANTY."
echo "You may redistribute it under certain conditions."
echo "See LICENSE for details."
echo
echo "Getperl downloads, configures, builds and tests perl."
echo "Project home page: http://github.com/rsp/getperl"
echo
if [ "$1" == "" ]; then
    echo "Usage: getperl VERSION"
    echo "       getperl VERSION PREFIX"
    echo
    echo "Downloads: http://www.cpan.org/src/5.0/perl-VERSION.tar.gz"
    echo "and builds for installation in PREFIX or /opt/perl by default."
    echo "If PREFIX is 'v' or 'V' it is equivalent to /opt/perl-VERSION"
    echo
    echo "Examples: getperl 5.12.2"
    echo "          getperl 5.12.2 v"
    echo "          getperl 5.12.2 /usr/local"
    echo
    exit 1
fi
version="$1"
dir="perl-$version"
file="$dir.tar.gz"
url="http://www.cpan.org/src/5.0/$file"
if [ "$2" == "" ]; then
    prefix="/opt/perl"
elif [ "$2" == "v" ] || [ "$2" == "V" ]; then
    prefix="/opt/perl-$version"
else
    prefix="$2"
fi
echo "Getperl is going to download:"
echo "    $url"
echo "and build it for installation in:"
echo "    $prefix"

d1=`date '+%Y-%m-%d %H:%M:%S'`
if [ -d $dir ]; then
    echo "Directory $dir already exists - remove manually"
    echo
    exit 2
fi
if [ -f $file ]; then
    echo "File $file already exists - skipping download"
else
    wget $url
fi
if [ ! -f $file ]; then
    echo "File $file not found - download failed"
    echo
    exit 2
fi
tar xzvf $file || (echo "Error extracting $file"; exit 2)
if [ ! -d $dir ]; then
    echo "Directory $dir not found - extraction failed"
    echo
    exit 2
fi
cd $dir
sh Configure -Dprefix=$prefix -de \
&& make && make test && echo DONE || (echo ERROR; exit 2)
d2=`date '+%Y-%m-%d %H:%M:%S'`
echo -e "From:\t$d1\nTo:\t$d2"
echo
echo "You can now run 'make install' or 'sudo make install'"
echo "to install $dir in $prefix"
echo

